package autumn.twilightforest.init.item

import autumn.twilightforest.TwilightForest
import autumn.twilightforest.init.block.TFBlocks
import net.fabricmc.fabric.api.itemgroup.v1.FabricItemGroup
import net.minecraft.item.ItemStack
import net.minecraft.registry.Registries
import net.minecraft.registry.Registry
import net.minecraft.text.Text
import net.minecraft.util.Identifier

object TFItemGroups {
    val TWILIGHT_FOREST_ITEMS_GROUP = Registry.register(Registries.ITEM_GROUP,
        Identifier.of(TwilightForest.MOD_ID, "twilight_forest_items"),
        FabricItemGroup.builder().icon { ItemStack(TFItems.MAGIC_MAP_FOCUS)}
            .displayName(Text.translatable("itemgroup.twilightforest.twilight_forest_items"))
            .entries {displayContext, entries ->
                entries.add(TFItems.NAGA_SCALE)
                entries.add(TFItems.LIVEROOT)
                entries.add(TFItems.RAW_IRONWOOD)
                entries.add(TFItems.IRONWOOD_INGOT)
                entries.add(TFItems.STEELEAF_INGOT)
                entries.add(TFItems.ARMOR_SHARD)
                entries.add(TFItems.ARMOR_SHARD_CLUSTER)
                entries.add(TFItems.KNIGHTMETAL_INGOT)
                entries.add(TFItems.FIERY_BLOOD)
                entries.add(TFItems.FIERY_TEARS)
                entries.add(TFItems.FIERY_INGOT)
                entries.add(TFItems.ARCTIC_FUR)
                entries.add(TFItems.ALPHA_YETI_FUR)

                entries.add(TFItems.RAVEN_FEATHER)
                entries.add(TFItems.MAGIC_MAP_FOCUS)
                entries.add(TFItems.MAZE_MAP_FOCUS)
                entries.add(TFItems.BORER_ESSENCE)
                entries.add(TFItems.CARMINITE)
                entries.add(TFItems.EMPERORS_CLOTH)
                entries.add(TFItems.CROWN_SPLINTER)

                entries.add(TFItems.TOWER_KEY)

                entries.add(TFItems.RAW_VENISON)
                entries.add(TFItems.COOKED_VENISON)
                entries.add(TFItems.RAW_MEEF)
                entries.add(TFItems.COOKED_MEEF)
                entries.add(TFItems.MEEF_STROGANOFF)
                entries.add(TFItems.HYDRA_CHOP)
                entries.add(TFItems.TORCHBERRIES)
                entries.add(TFItems.EXPERIMENT_115)
                entries.add(TFItems.MAZE_WAFER)

                entries.add(TFItems.TWILIGHT_OAK_BOAT)
                entries.add(TFItems.TWILIGHT_OAK_CHEST_BOAT)
                entries.add(TFItems.CANOPY_BOAT)
                entries.add(TFItems.CANOPY_CHEST_BOAT)
                entries.add(TFItems.TWILIGHT_MANGROVE_BOAT)
                entries.add(TFItems.TWILIGHT_MANGROVE_CHEST_BOAT)
                entries.add(TFItems.DARK_BOAT)
                entries.add(TFItems.DARK_CHEST_BOAT)
                entries.add(TFItems.TIME_BOAT)
                entries.add(TFItems.TIME_CHEST_BOAT)
                entries.add(TFItems.TRANSFORMATION_BOAT)
                entries.add(TFItems.TRANSFORMATION_CHEST_BOAT)
                entries.add(TFItems.MINING_BOAT)
                entries.add(TFItems.MINING_CHEST_BOAT)
                entries.add(TFItems.SORTING_BOAT)
                entries.add(TFItems.SORTING_CHEST_BOAT)
            }.build()
    )
    val TWILIGHT_FOREST_BLOCKS_GROUP = Registry.register(Registries.ITEM_GROUP,
        Identifier.of(TwilightForest.MOD_ID, "twilight_forest_blocks"),
        FabricItemGroup.builder().icon { ItemStack(TFBlocks.MOSSY_UNDERBRICK)}
            .displayName(Text.translatable("itemgroup.twilightforest.twilight_forest_blocks"))
            .entries {displayContext, entries ->
                entries.add(TFBlocks.ROOT_BLOCK)
                entries.add(TFBlocks.LIVEROOT_BLOCK)

                entries.add(TFBlocks.IRONWOOD_BLOCK)
                entries.add(TFBlocks.STEELEAF_BLOCK)
                entries.add(TFBlocks.KNIGHTMETAL_BLOCK)
                entries.add(TFBlocks.FIERY_BLOCK)
                entries.add(TFBlocks.ARCTIC_FUR_BLOCK)

                entries.add(TFBlocks.MAZESTONE)
                entries.add(TFBlocks.MAZESTONE_BRICK)
                entries.add(TFBlocks.MAZESTONE_LARGE_BRICK)
                entries.add(TFBlocks.CHISELED_MAZESTONE)
                entries.add(TFBlocks.CUT_MAZESTONE)
                entries.add(TFBlocks.DECORATIVE_MAZESTONE)
                entries.add(TFBlocks.CRACKED_MAZESTONE_BRICK)
                entries.add(TFBlocks.MOSSY_MAZESTONE_BRICK)
                entries.add(TFBlocks.MAZESTONE_MOSAIC)
                entries.add(TFBlocks.MAZESTONE_BORDER)

                entries.add(TFBlocks.UNDERBRICK)
                entries.add(TFBlocks.MOSSY_UNDERBRICK)
                entries.add(TFBlocks.CRACKED_UNDERBRICK)
                entries.add(TFBlocks.UNDERBRICK_FLOOR)

                entries.add(TFBlocks.TOWERWOOD)
                entries.add(TFBlocks.ENCASED_TOWERWOOD)
                entries.add(TFBlocks.CRACKED_TOWERWOOD)

                entries.add(TFBlocks.HEDGE)
                entries.add(TFBlocks.HEDGE_ROSE)

                entries.add(TFBlocks.STRONGHOLD_SHIELD);

                entries.add(TFBlocks.INFESTED_TOWERWOOD)
                entries.add(TFBlocks.ANTIBUILT_BLOCK)
                entries.add(TFBlocks.FAKE_GOLD)
                entries.add(TFBlocks.FAKE_DIAMOND)

                entries.add(TFBlocks.MAZE_SLIME_BLOCK)

                entries.add(TFBlocks.TWILIGHT_OAK_LOG)
                entries.add(TFBlocks.STRIPPED_TWILIGHT_OAK_LOG)
                entries.add(TFBlocks.TWILIGHT_OAK_LEAVES)
                entries.add(TFBlocks.TWILIGHT_OAK_SAPLING)
                entries.add(TFBlocks.TWILIGHT_OAK_PLANKS)
                entries.add(TFBlocks.TWILIGHT_OAK_DOOR)
                entries.add(TFBlocks.TWILIGHT_OAK_TRAPDOOR)
                entries.add(TFBlocks.TWILIGHT_OAK_FENCE)
                entries.add(TFBlocks.TWILIGHT_OAK_FENCE_GATE)
                entries.add(TFBlocks.TWILIGHT_OAK_STAIRS)
                entries.add(TFBlocks.TWILIGHT_OAK_SLAB)
                entries.add(TFBlocks.TWILIGHT_OAK_PRESSURE_PLATE)
                entries.add(TFBlocks.TWILIGHT_OAK_BUTTON)
                entries.add(TFItems.TWILIGHT_OAK_SIGN)
                entries.add(TFItems.TWILIGHT_OAK_HANGING_SIGN)

                entries.add(TFBlocks.CANOPY_LOG)
                entries.add(TFBlocks.STRIPPED_CANOPY_LOG)
                entries.add(TFBlocks.CANOPY_LEAVES)
                entries.add(TFBlocks.CANOPY_SAPLING)
                entries.add(TFBlocks.CANOPY_PLANKS)
                entries.add(TFBlocks.CANOPY_DOOR)
                entries.add(TFBlocks.CANOPY_TRAPDOOR)
                entries.add(TFBlocks.CANOPY_FENCE)
                entries.add(TFBlocks.CANOPY_FENCE_GATE)
                entries.add(TFBlocks.CANOPY_STAIRS)
                entries.add(TFBlocks.CANOPY_SLAB)
                entries.add(TFBlocks.CANOPY_PRESSURE_PLATE)
                entries.add(TFBlocks.CANOPY_BUTTON)
                entries.add(TFItems.CANOPY_SIGN)
                entries.add(TFItems.CANOPY_HANGING_SIGN)

                entries.add(TFBlocks.TWILIGHT_MANGROVE_LOG)
                entries.add(TFBlocks.STRIPPED_TWILIGHT_MANGROVE_LOG)
                entries.add(TFBlocks.TWILIGHT_MANGROVE_LEAVES)
                entries.add(TFBlocks.TWILIGHT_MANGROVE_SAPLING)
                entries.add(TFBlocks.TWILIGHT_MANGROVE_PLANKS)
                entries.add(TFBlocks.TWILIGHT_MANGROVE_DOOR)
                entries.add(TFBlocks.TWILIGHT_MANGROVE_TRAPDOOR)
                entries.add(TFBlocks.TWILIGHT_MANGROVE_FENCE)
                entries.add(TFBlocks.TWILIGHT_MANGROVE_FENCE_GATE)
                entries.add(TFBlocks.TWILIGHT_MANGROVE_STAIRS)
                entries.add(TFBlocks.TWILIGHT_MANGROVE_SLAB)
                entries.add(TFBlocks.TWILIGHT_MANGROVE_PRESSURE_PLATE)
                entries.add(TFBlocks.TWILIGHT_MANGROVE_BUTTON)
                entries.add(TFItems.TWILIGHT_MANGROVE_SIGN)
                entries.add(TFItems.TWILIGHT_MANGROVE_HANGING_SIGN)

                entries.add(TFBlocks.DARK_LOG)
                entries.add(TFBlocks.STRIPPED_DARK_LOG)
                entries.add(TFBlocks.DARK_LEAVES)
                entries.add(TFBlocks.DARK_SAPLING)
                entries.add(TFBlocks.DARK_PLANKS)
                entries.add(TFBlocks.DARK_DOOR)
                entries.add(TFBlocks.DARK_TRAPDOOR)
                entries.add(TFBlocks.DARK_FENCE)
                entries.add(TFBlocks.DARK_FENCE_GATE)
                entries.add(TFBlocks.DARK_STAIRS)
                entries.add(TFBlocks.DARK_SLAB)
                entries.add(TFBlocks.DARK_PRESSURE_PLATE)
                entries.add(TFBlocks.DARK_BUTTON)
                entries.add(TFItems.DARK_SIGN)
                entries.add(TFItems.DARK_HANGING_SIGN)

                entries.add(TFBlocks.TIME_LOG)
                entries.add(TFBlocks.STRIPPED_TIME_LOG)
                entries.add(TFBlocks.TIME_LEAVES)
                entries.add(TFBlocks.TIME_SAPLING)
                entries.add(TFBlocks.TIME_PLANKS)
                entries.add(TFBlocks.TIME_DOOR)
                entries.add(TFBlocks.TIME_TRAPDOOR)
                entries.add(TFBlocks.TIME_FENCE)
                entries.add(TFBlocks.TIME_FENCE_GATE)
                entries.add(TFBlocks.TIME_STAIRS)
                entries.add(TFBlocks.TIME_SLAB)
                entries.add(TFBlocks.TIME_PRESSURE_PLATE)
                entries.add(TFBlocks.TIME_BUTTON)
                entries.add(TFItems.TIME_SIGN)
                entries.add(TFItems.TIME_HANGING_SIGN)

                entries.add(TFBlocks.TRANSFORMATION_LOG)
                entries.add(TFBlocks.STRIPPED_TRANSFORMATION_LOG)
                entries.add(TFBlocks.TRANSFORMATION_LEAVES)
                entries.add(TFBlocks.TRANSFORMATION_SAPLING)
                entries.add(TFBlocks.TRANSFORMATION_PLANKS)
                entries.add(TFBlocks.TRANSFORMATION_DOOR)
                entries.add(TFBlocks.TRANSFORMATION_TRAPDOOR)
                entries.add(TFBlocks.TRANSFORMATION_FENCE)
                entries.add(TFBlocks.TRANSFORMATION_FENCE_GATE)
                entries.add(TFBlocks.TRANSFORMATION_STAIRS)
                entries.add(TFBlocks.TRANSFORMATION_SLAB)
                entries.add(TFBlocks.TRANSFORMATION_PRESSURE_PLATE)
                entries.add(TFBlocks.TRANSFORMATION_BUTTON)
                entries.add(TFItems.TRANSFORMATION_SIGN)
                entries.add(TFItems.TRANSFORMATION_HANGING_SIGN)

                entries.add(TFBlocks.MINING_LOG)
                entries.add(TFBlocks.STRIPPED_MINING_LOG)
                entries.add(TFBlocks.MINING_LEAVES)
                entries.add(TFBlocks.MINING_SAPLING)
                entries.add(TFBlocks.MINING_PLANKS)
                entries.add(TFBlocks.MINING_DOOR)
                entries.add(TFBlocks.MINING_TRAPDOOR)
                entries.add(TFBlocks.MINING_FENCE)
                entries.add(TFBlocks.MINING_FENCE_GATE)
                entries.add(TFBlocks.MINING_STAIRS)
                entries.add(TFBlocks.MINING_SLAB)
                entries.add(TFBlocks.MINING_PRESSURE_PLATE)
                entries.add(TFBlocks.MINING_BUTTON)
                entries.add(TFItems.MINING_SIGN)
                entries.add(TFItems.MINING_HANGING_SIGN)

                entries.add(TFBlocks.SORTING_LOG)
                entries.add(TFBlocks.STRIPPED_SORTING_LOG)
                entries.add(TFBlocks.SORTING_LEAVES)
                entries.add(TFBlocks.SORTING_SAPLING)
                entries.add(TFBlocks.SORTING_PLANKS)
                entries.add(TFBlocks.SORTING_DOOR)
                entries.add(TFBlocks.SORTING_TRAPDOOR)
                entries.add(TFBlocks.SORTING_FENCE)
                entries.add(TFBlocks.SORTING_FENCE_GATE)
                entries.add(TFBlocks.SORTING_STAIRS)
                entries.add(TFBlocks.SORTING_SLAB)
                entries.add(TFBlocks.SORTING_PRESSURE_PLATE)
                entries.add(TFBlocks.SORTING_BUTTON)
                entries.add(TFItems.SORTING_SIGN)
                entries.add(TFItems.SORTING_HANGING_SIGN)
            }.build()
    )
    val TWILIGHT_FOREST_EQUIPMENT_GROUP = Registry.register(Registries.ITEM_GROUP,
        Identifier.of(TwilightForest.MOD_ID, "twilight_forest_equipment"),
        FabricItemGroup.builder().icon { ItemStack(TFItems.POCKET_WATCH)}
            .displayName(Text.translatable("itemgroup.twilightforest.twilight_forest_equipment"))
            .entries {displayContext, entries ->
                entries.add(TFItems.POCKET_WATCH)
                entries.add(TFItems.CHARM_OF_LIFE_I)
                entries.add(TFItems.CHARM_OF_LIFE_II)
                entries.add(TFItems.CHARM_OF_KEEPING_I)
                entries.add(TFItems.CHARM_OF_KEEPING_II)
                entries.add(TFItems.CHARM_OF_KEEPING_III)

                entries.add(TFItems.NAGA_LEGGINGS)
                entries.add(TFItems.NAGA_CHESTPLATE)

                entries.add(TFItems.IRONWOOD_BOOTS)
                entries.add(TFItems.IRONWOOD_LEGGINGS)
                entries.add(TFItems.IRONWOOD_CHESTPLATE)
                entries.add(TFItems.IRONWOOD_HELMET)
                entries.add(TFItems.IRONWOOD_SWORD)
                entries.add(TFItems.IRONWOOD_PICKAXE)
                entries.add(TFItems.IRONWOOD_SHOVEL)
                entries.add(TFItems.IRONWOOD_AXE)
                entries.add(TFItems.IRONWOOD_HOE)

                entries.add(TFItems.STEELEAF_BOOTS)
                entries.add(TFItems.STEELEAF_LEGGINGS)
                entries.add(TFItems.STEELEAF_CHESTPLATE)
                entries.add(TFItems.STEELEAF_HELMET)
                entries.add(TFItems.STEELEAF_SWORD)
                entries.add(TFItems.STEELEAF_PICKAXE)
                entries.add(TFItems.STEELEAF_SHOVEL)
                entries.add(TFItems.STEELEAF_AXE)
                entries.add(TFItems.STEELEAF_HOE)

                entries.add(TFItems.GOLD_MINOTAUR_AXE)
                entries.add(TFItems.DIAMOND_MINOTAUR_AXE)
                entries.add(TFItems.MAZEBREAKER_PICKAXE)

                entries.add(TFItems.KNIGHTMETAL_BOOTS)
                entries.add(TFItems.KNIGHTMETAL_LEGGINGS)
                entries.add(TFItems.KNIGHTMETAL_CHESTPLATE)
                entries.add(TFItems.KNIGHTMETAL_HELMET)
                entries.add(TFItems.KNIGHTMETAL_SWORD)
                entries.add(TFItems.KNIGHTMETAL_PICKAXE)
                entries.add(TFItems.KNIGHTMETAL_AXE)
                entries.add(TFItems.PHANTOM_CHESTPLATE)
                entries.add(TFItems.PHANTOM_HELMET)

                entries.add(TFItems.FIERY_BOOTS)
                entries.add(TFItems.FIERY_LEGGINGS)
                entries.add(TFItems.FIERY_CHESTPLATE)
                entries.add(TFItems.FIERY_HELMET)
                entries.add(TFItems.FIERY_SWORD)
                entries.add(TFItems.FIERY_PICKAXE)

                entries.add(TFItems.ARCTIC_BOOTS)
                entries.add(TFItems.ARCTIC_LEGGINGS)
                entries.add(TFItems.ARCTIC_CHESTPLATE)
                entries.add(TFItems.ARCTIC_HELMET)

                entries.add(TFItems.YETI_BOOTS)
                entries.add(TFItems.YETI_LEGGINGS)
                entries.add(TFItems.YETI_CHESTPLATE)
                entries.add(TFItems.YETI_HELMET)
            }.build()
    )

    fun registerItemGroups() {
        TwilightForest.logger?.info("Registering item groups for " + TwilightForest.MOD_ID)
    }
}