package autumn.twilightforest.datagen.providers

import autumn.twilightforest.TwilightForest
import autumn.twilightforest.init.block.TFBlocks
import autumn.twilightforest.init.entity.TFEntities
import autumn.twilightforest.init.item.TFItems
import net.fabricmc.fabric.api.datagen.v1.FabricDataOutput
import net.fabricmc.fabric.api.datagen.v1.provider.FabricLanguageProvider
import net.minecraft.registry.RegistryWrapper
import net.minecraft.text.Text
import net.minecraft.text.TranslatableTextContent
import java.util.concurrent.CompletableFuture

class TFEnglishLanguageProvider(output: FabricDataOutput, registryLookup: CompletableFuture<RegistryWrapper.WrapperLookup>) : FabricLanguageProvider(output, registryLookup) {

    private fun addText(builder: TranslationBuilder?, text: Text, value: String) {
        val content = text.content
        if (content is TranslatableTextContent) {
            builder?.add(content.key, value)
        } else {
            TwilightForest.logger?.warn("Failed to add translation for text: {}", text.string)
        }
    }

    override fun generateTranslations(p0: RegistryWrapper.WrapperLookup?, entries: TranslationBuilder?) {
        entries?.add(TFItems.NAGA_SCALE, "Naga Scale")
        entries?.add(TFItems.LIVEROOT, "Liveroot")
        entries?.add(TFItems.RAW_IRONWOOD, "Raw Ironwood")
        entries?.add(TFItems.IRONWOOD_INGOT, "Ironwood Ingot")
        entries?.add(TFItems.STEELEAF_INGOT, "Steeleaf Ingot")
        entries?.add(TFItems.ARMOR_SHARD, "Armor Shard")
        entries?.add(TFItems.ARMOR_SHARD_CLUSTER, "Armor Shard Cluster")
        entries?.add(TFItems.KNIGHTMETAL_INGOT, "Knightmetal Ingot")
        entries?.add(TFItems.FIERY_BLOOD, "Fiery Blood")
        entries?.add(TFItems.FIERY_TEARS, "Fiery Tears")
        entries?.add(TFItems.FIERY_INGOT, "Fiery Ingot")
        entries?.add(TFItems.ARCTIC_FUR, "Arctic Fur")
        entries?.add(TFItems.ALPHA_YETI_FUR, "Alpha Yeti Fur")

        entries?.add(TFItems.RAVEN_FEATHER, "Raven Feather")
        entries?.add(TFItems.MAGIC_MAP_FOCUS, "Magic Map Focus")
        entries?.add(TFItems.MAZE_MAP_FOCUS, "Maze Map Focus")
        entries?.add(TFItems.CHARM_OF_LIFE_I, "Charm of Life I")
        entries?.add(TFItems.CHARM_OF_LIFE_II, "Charm of Life II")
        entries?.add(TFItems.CHARM_OF_KEEPING_I, "Charm of Keeping I")
        entries?.add(TFItems.CHARM_OF_KEEPING_II, "Charm of Keeping II")
        entries?.add(TFItems.CHARM_OF_KEEPING_III, "Charm of Keeping II")
        entries?.add(TFItems.BORER_ESSENCE, "Borer Essence")
        entries?.add(TFItems.CARMINITE, "Carminite")
        entries?.add(TFItems.EMPERORS_CLOTH, "Emperor's Cloth")
        entries?.add(TFItems.CROWN_SPLINTER, "Crown Splinter")

        entries?.add(TFItems.TOWER_KEY, "Tower Key")

        entries?.add(TFItems.RAW_VENISON, "Raw Venison")
        entries?.add(TFItems.COOKED_VENISON, "Venison Steak")
        entries?.add(TFItems.RAW_MEEF, "Raw Meef")
        entries?.add(TFItems.COOKED_MEEF, "Meef Steak")
        entries?.add(TFItems.MEEF_STROGANOFF, "Meef Stroganoff")
        entries?.add(TFItems.HYDRA_CHOP, "Hydra Chop")
        entries?.add(TFItems.TORCHBERRIES, "Torchberries")
        entries?.add(TFItems.EXPERIMENT_115, "Experiment 115")
        entries?.add(TFItems.MAZE_WAFER, "Maze Wafer")

        entries?.add(TFItems.POCKET_WATCH, "Rabbit's Pocket Watch")

        entries?.add(TFItems.NAGA_LEGGINGS, "Naga Leggings")
        entries?.add(TFItems.NAGA_CHESTPLATE, "Naga Chestplate")

        entries?.add(TFItems.IRONWOOD_BOOTS, "Ironwood Boots")
        entries?.add(TFItems.IRONWOOD_LEGGINGS, "Ironwood Leggings")
        entries?.add(TFItems.IRONWOOD_CHESTPLATE, "Ironwood Chestplate")
        entries?.add(TFItems.IRONWOOD_HELMET, "Ironwood Helmet")
        entries?.add(TFItems.IRONWOOD_SWORD, "Ironwood Sword")
        entries?.add(TFItems.IRONWOOD_PICKAXE ,"Ironwood Pickaxe")
        entries?.add(TFItems.IRONWOOD_SHOVEL, "Ironwood Shovel")
        entries?.add(TFItems.IRONWOOD_AXE, "Ironwood Axe")
        entries?.add(TFItems.IRONWOOD_HOE, "Ironwood Hoe")

        entries?.add(TFItems.STEELEAF_BOOTS, "Steeleaf Boots")
        entries?.add(TFItems.STEELEAF_LEGGINGS, "Steeleaf Leggings")
        entries?.add(TFItems.STEELEAF_CHESTPLATE, "Steeleaf Chestplate")
        entries?.add(TFItems.STEELEAF_HELMET, "Steeleaf Helmet")
        entries?.add(TFItems.STEELEAF_SWORD, "Steeleaf Sword")
        entries?.add(TFItems.STEELEAF_PICKAXE, "Steeleaf Pickaxe")
        entries?.add(TFItems.STEELEAF_SHOVEL, "Steeleaf Shovel")
        entries?.add(TFItems.STEELEAF_AXE, "Steeleaf Axe")
        entries?.add(TFItems.STEELEAF_HOE, "Steeleaf Hoe")

        entries?.add(TFItems.GOLD_MINOTAUR_AXE, "Gold Minotaur Axe")
        entries?.add(TFItems.DIAMOND_MINOTAUR_AXE, "Diamond Minotaur Axe")
        entries?.add(TFItems.MAZEBREAKER_PICKAXE, "Mazebreaker")

        entries?.add(TFItems.KNIGHTMETAL_BOOTS, "Knightmetal Boots")
        entries?.add(TFItems.KNIGHTMETAL_LEGGINGS, "Knightmetal Leggings")
        entries?.add(TFItems.KNIGHTMETAL_CHESTPLATE, "Knightmetal Chestplate")
        entries?.add(TFItems.KNIGHTMETAL_HELMET, "Knightmetal Helmet")
        entries?.add(TFItems.KNIGHTMETAL_SWORD, "Knightmetal Sword")
        entries?.add(TFItems.KNIGHTMETAL_PICKAXE, "Knightmetal Pickaxe")
        entries?.add(TFItems.KNIGHTMETAL_AXE, "Knightmetal Axe")
        entries?.add(TFItems.PHANTOM_CHESTPLATE, "Phantom Chestplate")
        entries?.add(TFItems.PHANTOM_HELMET, "Phantom Helmet")

        entries?.add(TFItems.FIERY_BOOTS, "Fiery Boots")
        entries?.add(TFItems.FIERY_LEGGINGS, "Fiery Leggings")
        entries?.add(TFItems.FIERY_CHESTPLATE, "Fiery Chestplate")
        entries?.add(TFItems.FIERY_HELMET, "Fiery Helmet")
        entries?.add(TFItems.FIERY_SWORD, "Fiery Sword")
        entries?.add(TFItems.FIERY_PICKAXE, "Fiery Pickaxe")

        entries?.add(TFItems.ARCTIC_BOOTS, "Arctic Boots")
        entries?.add(TFItems.ARCTIC_LEGGINGS, "Arctic Leggings")
        entries?.add(TFItems.ARCTIC_CHESTPLATE, "Arctic Chestplate")
        entries?.add(TFItems.ARCTIC_HELMET, "Arctic Helmet")

        entries?.add(TFItems.YETI_BOOTS, "Yeti Boots")
        entries?.add(TFItems.YETI_LEGGINGS, "Yeti Leggings")
        entries?.add(TFItems.YETI_CHESTPLATE, "Yeti Chestplate")
        entries?.add(TFItems.YETI_HELMET ,"Yeti Helmet")

        entries?.add(TFBlocks.ROOT_BLOCK.asItem(), "Root Block")
        entries?.add(TFBlocks.LIVEROOT_BLOCK.asItem(), "Liveroot Block")

        entries?.add(TFBlocks.IRONWOOD_BLOCK.asItem(), "Block of Ironwood")
        entries?.add(TFBlocks.STEELEAF_BLOCK.asItem(), "Block of Steeleaf")
        entries?.add(TFBlocks.KNIGHTMETAL_BLOCK.asItem(), "Block of Knightmetal")
        entries?.add(TFBlocks.FIERY_BLOCK.asItem(), "Block of Fiery Metal")
        entries?.add(TFBlocks.ARCTIC_FUR_BLOCK.asItem(), "Block of Arctic Fur")

        entries?.add(TFBlocks.MAZESTONE.asItem(), "Mazestone")
        entries?.add(TFBlocks.MAZESTONE_BRICK.asItem(), "Mazestone Brick")
        entries?.add(TFBlocks.MAZESTONE_LARGE_BRICK.asItem(), "Large Mazestone Brick")
        entries?.add(TFBlocks.CHISELED_MAZESTONE.asItem(), "Chiseled Mazestone")
        entries?.add(TFBlocks.CUT_MAZESTONE.asItem(), "Cut Mazestone")
        entries?.add(TFBlocks.DECORATIVE_MAZESTONE.asItem(), "Decorative Mazestone")
        entries?.add(TFBlocks.CRACKED_MAZESTONE_BRICK.asItem(), "Cracked Mazestone Brick")
        entries?.add(TFBlocks.MOSSY_MAZESTONE_BRICK.asItem(), "Mossy Mazestone Brick")
        entries?.add(TFBlocks.MAZESTONE_MOSAIC.asItem(), "Mazestone Mosaic")
        entries?.add(TFBlocks.MAZESTONE_BORDER.asItem(), "Mazestone Border")

        entries?.add(TFBlocks.UNDERBRICK.asItem(), "Underbrick")
        entries?.add(TFBlocks.MOSSY_UNDERBRICK.asItem(), "Mossy Underbrick")
        entries?.add(TFBlocks.CRACKED_UNDERBRICK.asItem(), "Cracked Underbrick")
        entries?.add(TFBlocks.UNDERBRICK_FLOOR.asItem(), "Underbrick Floor")

        entries?.add(TFBlocks.TOWERWOOD.asItem(), "Towerwood")
        entries?.add(TFBlocks.ENCASED_TOWERWOOD.asItem(), "Encased Towerwood")
        entries?.add(TFBlocks.CRACKED_TOWERWOOD.asItem(), "Cracked Towerwood")

        entries?.add(TFBlocks.HEDGE.asItem(), "Hedge")
        entries?.add(TFBlocks.HEDGE_ROSE.asItem(), "Flowering Hedge")

        entries?.add(TFBlocks.STRONGHOLD_SHIELD.asItem(), "Stronghold Shield")

        entries?.add(TFBlocks.INFESTED_TOWERWOOD.asItem(), "Infested Towerwood")
        entries?.add(TFBlocks.ANTIBUILT_BLOCK.asItem(), "Antibuilt Block")
        entries?.add(TFBlocks.FAKE_GOLD.asItem(), "Fake Gold")
        entries?.add(TFBlocks.FAKE_DIAMOND.asItem(), "Fake Diamond")

        entries?.add(TFBlocks.MAZE_SLIME_BLOCK.asItem(), "Maze Slime Block")

        entries?.add(TFBlocks.TWILIGHT_OAK_LOG.asItem(), "Twilight Oak Log")
        entries?.add(TFBlocks.STRIPPED_TWILIGHT_OAK_LOG.asItem(), "Stripped Twilight Oak Log")
        entries?.add(TFBlocks.TWILIGHT_OAK_LEAVES.asItem(), "Twilight Oak Leaves")
        entries?.add(TFBlocks.TWILIGHT_OAK_SAPLING.asItem(), "Twilight Oak Sapling")
        entries?.add(TFBlocks.TWILIGHT_OAK_PLANKS.asItem(), "Twilight Oak Planks")
        entries?.add(TFBlocks.TWILIGHT_OAK_DOOR.asItem(), "Twilight Oak Door")
        entries?.add(TFBlocks.TWILIGHT_OAK_TRAPDOOR.asItem(), "Twilight Oak Trapdoor")
        entries?.add(TFBlocks.TWILIGHT_OAK_FENCE.asItem(), "Twilight Oak Fence")
        entries?.add(TFBlocks.TWILIGHT_OAK_FENCE_GATE.asItem(), "Twilight Oak Fence Gate")
        entries?.add(TFBlocks.TWILIGHT_OAK_STAIRS.asItem(), "Twilight Oak Stairs")
        entries?.add(TFBlocks.TWILIGHT_OAK_SLAB.asItem(), "Twilight Oak Slab")
        entries?.add(TFBlocks.TWILIGHT_OAK_PRESSURE_PLATE.asItem(), "Twilight Oak Pressure Plate")
        entries?.add(TFBlocks.TWILIGHT_OAK_BUTTON.asItem(), "Twilight Oak Button")
        entries?.add(TFItems.TWILIGHT_OAK_SIGN, "Twilight Oak Sign")
        entries?.add(TFItems.TWILIGHT_OAK_HANGING_SIGN, "Twilight Oak Hanging Sign")
        entries?.add(TFItems.TWILIGHT_OAK_BOAT, "Twilight Oak Boat")
        entries?.add(TFItems.TWILIGHT_OAK_CHEST_BOAT, "Twilight Oak Chest Boat")
        addText(entries, Text.translatable("entity.twilightforest.twilight_oak_chest_boat"), "Twilight Oak Chest Boat")

        entries?.add(TFBlocks.CANOPY_LOG.asItem(), "Canopy Log")
        entries?.add(TFBlocks.STRIPPED_CANOPY_LOG.asItem(), "Stripped Canopy Log")
        entries?.add(TFBlocks.CANOPY_LEAVES.asItem(), "Canopy Leaves")
        entries?.add(TFBlocks.CANOPY_SAPLING.asItem(), "Canopy Sapling")
        entries?.add(TFBlocks.CANOPY_PLANKS.asItem(), "Canopy Planks")
        entries?.add(TFBlocks.CANOPY_DOOR.asItem(), "Canopy Door")
        entries?.add(TFBlocks.CANOPY_TRAPDOOR.asItem(), "Canopy Trapdoor")
        entries?.add(TFBlocks.CANOPY_FENCE.asItem(), "Canopy Fence")
        entries?.add(TFBlocks.CANOPY_FENCE_GATE.asItem(), "Canopy Fence Gate")
        entries?.add(TFBlocks.CANOPY_STAIRS.asItem(), "Canopy Stairs")
        entries?.add(TFBlocks.CANOPY_SLAB.asItem(), "Canopy Slab")
        entries?.add(TFBlocks.CANOPY_PRESSURE_PLATE.asItem(), "Canopy Pressure Plate")
        entries?.add(TFBlocks.CANOPY_BUTTON.asItem(), "Canopy Button")
        entries?.add(TFItems.CANOPY_SIGN, "Canopy Sign")
        entries?.add(TFItems.CANOPY_HANGING_SIGN, "Canopy Hanging Sign")
        entries?.add(TFItems.CANOPY_BOAT, "Canopy Boat")
        entries?.add(TFItems.CANOPY_CHEST_BOAT, "Canopy Chest Boat")
        addText(entries, Text.translatable("entity.twilightforest.canopy_chest_boat"), "Canopy Chest Boat")

        entries?.add(TFBlocks.TWILIGHT_MANGROVE_LOG.asItem(), "Twilight Mangrove Log")
        entries?.add(TFBlocks.STRIPPED_TWILIGHT_MANGROVE_LOG.asItem(), "Stripped Twilight Mangrove Log")
        entries?.add(TFBlocks.TWILIGHT_MANGROVE_LEAVES.asItem(), "Twilight Mangrove Leaves")
        entries?.add(TFBlocks.TWILIGHT_MANGROVE_SAPLING.asItem(), "Twilight Mangrove Sapling")
        entries?.add(TFBlocks.TWILIGHT_MANGROVE_PLANKS.asItem(), "Twilight Mangrove Planks")
        entries?.add(TFBlocks.TWILIGHT_MANGROVE_DOOR.asItem(), "Twilight Mangrove Door")
        entries?.add(TFBlocks.TWILIGHT_MANGROVE_TRAPDOOR.asItem(), "Twilight Mangrove Trapdoor")
        entries?.add(TFBlocks.TWILIGHT_MANGROVE_FENCE.asItem(), "Twilight Mangrove Fence")
        entries?.add(TFBlocks.TWILIGHT_MANGROVE_FENCE_GATE.asItem(), "Twilight Mangrove Fence Gate")
        entries?.add(TFBlocks.TWILIGHT_MANGROVE_STAIRS.asItem(), "Twilight Mangrove Stairs")
        entries?.add(TFBlocks.TWILIGHT_MANGROVE_SLAB.asItem(), "Twilight Mangrove Slab")
        entries?.add(TFBlocks.TWILIGHT_MANGROVE_PRESSURE_PLATE.asItem(), "Twilight Mangrove Pressure Plate")
        entries?.add(TFBlocks.TWILIGHT_MANGROVE_BUTTON.asItem(), "Twilight Mangrove Button")
        entries?.add(TFItems.TWILIGHT_MANGROVE_SIGN, "Twilight Mangrove Sign")
        entries?.add(TFItems.TWILIGHT_MANGROVE_HANGING_SIGN, "Twilight Mangrove Hanging Sign")
        entries?.add(TFItems.TWILIGHT_MANGROVE_BOAT, "Twilight Mangrove Boat")
        entries?.add(TFItems.TWILIGHT_MANGROVE_CHEST_BOAT, "Twilight Mangrove Chest Boat")
        addText(entries, Text.translatable("entity.twilightforest.twilight_mangrove_chest_boat"), "Twilight Mangrove Chest Boat")

        entries?.add(TFBlocks.DARK_LOG.asItem(), "Dark Log")
        entries?.add(TFBlocks.STRIPPED_DARK_LOG.asItem(), "Stripped Dark Log")
        entries?.add(TFBlocks.DARK_LEAVES.asItem(), "Darkwood Leaves")
        entries?.add(TFBlocks.DARK_SAPLING.asItem(), "Darkwood Sapling")
        entries?.add(TFBlocks.DARK_PLANKS.asItem(), "Dark Planks")
        entries?.add(TFBlocks.DARK_DOOR.asItem(), "Darkwood Door")
        entries?.add(TFBlocks.DARK_TRAPDOOR.asItem(), "Darkwood Trapdoor")
        entries?.add(TFBlocks.DARK_FENCE.asItem(), "Dark Fence")
        entries?.add(TFBlocks.DARK_FENCE_GATE.asItem(), "Dark Fence Gate")
        entries?.add(TFBlocks.DARK_STAIRS.asItem(), "Dark Stairs")
        entries?.add(TFBlocks.DARK_SLAB.asItem(), "Dark Slab")
        entries?.add(TFBlocks.DARK_PRESSURE_PLATE.asItem(), "Dark Pressure Plate")
        entries?.add(TFBlocks.DARK_BUTTON.asItem(), "Dark Button")
        entries?.add(TFItems.DARK_SIGN, "Dark Sign")
        entries?.add(TFItems.DARK_HANGING_SIGN, "Dark Hanging Sign")
        entries?.add(TFItems.DARK_BOAT, "Dark Boat")
        entries?.add(TFItems.DARK_CHEST_BOAT, "Dark Chest Boat")
        addText(entries, Text.translatable("entity.twilightforest.dark_chest_boat"), "Dark Chest Boat")

        entries?.add(TFBlocks.TIME_LOG.asItem(), "Time Log")
        entries?.add(TFBlocks.STRIPPED_TIME_LOG.asItem(), "Stripped Time Log")
        entries?.add(TFBlocks.TIME_LEAVES.asItem(), "Timewood Leaves")
        entries?.add(TFBlocks.TIME_SAPLING.asItem(), "Timewood Sapling")
        entries?.add(TFBlocks.TIME_PLANKS.asItem(), "Time Planks")
        entries?.add(TFBlocks.TIME_DOOR.asItem(), "Timewood Door")
        entries?.add(TFBlocks.TIME_TRAPDOOR.asItem(), "Timewood Trapdoor")
        entries?.add(TFBlocks.TIME_FENCE.asItem(), "Time Fence")
        entries?.add(TFBlocks.TIME_FENCE_GATE.asItem(), "Time Fence Gate")
        entries?.add(TFBlocks.TIME_STAIRS.asItem(), "Time Stairs")
        entries?.add(TFBlocks.TIME_SLAB.asItem(), "Time Slab")
        entries?.add(TFBlocks.TIME_PRESSURE_PLATE.asItem(), "Time Pressure Plate")
        entries?.add(TFBlocks.TIME_BUTTON.asItem(), "Time Button")
        entries?.add(TFItems.TIME_SIGN, "Time Sign")
        entries?.add(TFItems.TIME_HANGING_SIGN, "Time Hanging Sign")
        entries?.add(TFItems.TIME_BOAT, "Time Boat")
        entries?.add(TFItems.TIME_CHEST_BOAT, "Time Chest Boat")
        addText(entries, Text.translatable("entity.twilightforest.time_chest_boat"), "Time Chest Boat")

        entries?.add(TFBlocks.TRANSFORMATION_LOG.asItem(), "Transformation Log")
        entries?.add(TFBlocks.STRIPPED_TRANSFORMATION_LOG.asItem(), "Stripped Transformation Log")
        entries?.add(TFBlocks.TRANSFORMATION_LEAVES.asItem(), "Transformation Leaves")
        entries?.add(TFBlocks.TRANSFORMATION_SAPLING.asItem(), "Transformation Sapling")
        entries?.add(TFBlocks.TRANSFORMATION_PLANKS.asItem(), "Transformation Planks")
        entries?.add(TFBlocks.TRANSFORMATION_DOOR.asItem(), "Transformation Door")
        entries?.add(TFBlocks.TRANSFORMATION_TRAPDOOR.asItem(), "Transformation Trapdoor")
        entries?.add(TFBlocks.TRANSFORMATION_FENCE.asItem(), "Transformation Fence")
        entries?.add(TFBlocks.TRANSFORMATION_FENCE_GATE.asItem(), "Transformation Fence Gate")
        entries?.add(TFBlocks.TRANSFORMATION_STAIRS.asItem(), "Transformation Stairs")
        entries?.add(TFBlocks.TRANSFORMATION_SLAB.asItem(), "Transformation Slab")
        entries?.add(TFBlocks.TRANSFORMATION_PRESSURE_PLATE.asItem(), "Transformation Pressure Plate")
        entries?.add(TFBlocks.TRANSFORMATION_BUTTON.asItem(), "Transformation Button")
        entries?.add(TFItems.TRANSFORMATION_SIGN, "Transformation Sign")
        entries?.add(TFItems.TRANSFORMATION_HANGING_SIGN, "Transformation Hanging Sign")
        entries?.add(TFItems.TRANSFORMATION_BOAT, "Transformation Boat")
        entries?.add(TFItems.TRANSFORMATION_CHEST_BOAT, "Transformation Chest Boat")
        addText(entries, Text.translatable("entity.twilightforest.transformation_chest_boat"), "Transformation Chest Boat")

        entries?.add(TFBlocks.MINING_LOG.asItem(), "Mining Log")
        entries?.add(TFBlocks.STRIPPED_MINING_LOG.asItem(), "Stripped Mining Log")
        entries?.add(TFBlocks.MINING_LEAVES.asItem(), "Miningwood Leaves")
        entries?.add(TFBlocks.MINING_SAPLING.asItem(), "Miningwood Sapling")
        entries?.add(TFBlocks.MINING_PLANKS.asItem(), "Mining Planks")
        entries?.add(TFBlocks.MINING_DOOR.asItem(), "Miningwood Door")
        entries?.add(TFBlocks.MINING_TRAPDOOR.asItem(), "Miningwood Trapdoor")
        entries?.add(TFBlocks.MINING_FENCE.asItem(), "Mining Fence")
        entries?.add(TFBlocks.MINING_FENCE_GATE.asItem(), "Mining Fence Gate")
        entries?.add(TFBlocks.MINING_STAIRS.asItem(), "Mining Stairs")
        entries?.add(TFBlocks.MINING_SLAB.asItem(), "Mining Slab")
        entries?.add(TFBlocks.MINING_PRESSURE_PLATE.asItem(), "Mining Pressure Plate")
        entries?.add(TFBlocks.MINING_BUTTON.asItem(), "Mining Button")
        entries?.add(TFItems.MINING_SIGN, "Mining Sign")
        entries?.add(TFItems.MINING_HANGING_SIGN, "Mining Hanging Sign")
        entries?.add(TFItems.MINING_BOAT, "Mining Boat")
        entries?.add(TFItems.MINING_CHEST_BOAT, "Mining Chest Boat")
        addText(entries, Text.translatable("entity.twilightforest.mining_chest_boat"), "Mining Chest Boat")

        entries?.add(TFBlocks.SORTING_LOG.asItem(), "Sorting Log")
        entries?.add(TFBlocks.STRIPPED_SORTING_LOG.asItem(), "Stripped Sorting Log")
        entries?.add(TFBlocks.SORTING_LEAVES.asItem(), "Sortingwood Leaves")
        entries?.add(TFBlocks.SORTING_SAPLING.asItem(), "Sortingwood Sapling")
        entries?.add(TFBlocks.SORTING_PLANKS.asItem(), "Sorting Planks")
        entries?.add(TFBlocks.SORTING_DOOR.asItem(), "Sortingwood Door")
        entries?.add(TFBlocks.SORTING_TRAPDOOR.asItem(), "Sortingwood Trapdoor")
        entries?.add(TFBlocks.SORTING_FENCE.asItem(), "Sorting Fence")
        entries?.add(TFBlocks.SORTING_FENCE_GATE.asItem(), "Sorting Fence Gate")
        entries?.add(TFBlocks.SORTING_STAIRS.asItem(), "Sorting Stairs")
        entries?.add(TFBlocks.SORTING_SLAB.asItem(), "Sorting Slab")
        entries?.add(TFBlocks.SORTING_PRESSURE_PLATE.asItem(), "Sorting Pressure Plate")
        entries?.add(TFBlocks.SORTING_BUTTON.asItem(), "Sorting Button")
        entries?.add(TFItems.SORTING_SIGN, "Sorting Sign")
        entries?.add(TFItems.SORTING_HANGING_SIGN, "Sorting Hanging Sign")
        entries?.add(TFItems.SORTING_BOAT, "Sorting Boat")
        entries?.add(TFItems.SORTING_CHEST_BOAT, "Sorting Chest Boat")
        addText(entries, Text.translatable("entity.twilightforest.sorting_chest_boat"), "Sorting Chest Boat")

        entries?.add(TFEntities.DWARF_RABBIT, "Dwarf Rabbit")

        addText(entries, Text.translatable("itemgroup.twilightforest.twilight_forest_items"), "Twilight Forest: Items")
        addText(entries, Text.translatable("itemgroup.twilightforest.twilight_forest_blocks"), "Twilight Forest: Blocks")
        addText(entries, Text.translatable("itemgroup.twilightforest.twilight_forest_equipment"), "Twilight Forest: Equipment")

        addText(entries,Text.translatable("tooltip.twilightforest.experiment_115.tooltip"), "It's not quite cake...")
        addText(entries,Text.translatable("tooltip.twilightforest.pocket_watch.tooltip"), "It seems to always be running late")
        addText(entries,Text.translatable("tooltip.twilightforest.arctic_fur_block.tooltip"), "Here for your own safety!")
        addText(entries,Text.translatable("tooltip.twilightforest.fiery_block.tooltip"), "Watch your step...")
        addText(entries,Text.translatable("tooltip.twilightforest.knightmetal_block.tooltip"), "The cactus but more METAL!")
    }
}